#!/usr/bin/env bash
# lib/generate.sh — Containerfile generator (ARCHITECTURE.md §7–§9).
#
# Provides:
#   layer_output_name        $1 layer id -> generated/<name> directory name
#   layer_context_dir        $1 layer id -> abs path of the podman build context
#   emit_layer_containerfile $1 layer id -> writes generated/<name>/Containerfile
#   generate_image           $1 purpose id -> emits every Containerfile in its chain
#
# Requires lib/common.sh sourced and load_build_conf already called.

set -euo pipefail

# shellcheck source=common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/common.sh"

# ---------------------------------------------------------------------------
# Naming and context resolution
# ---------------------------------------------------------------------------

# layer_output_name — $1 = layer id -> name of the generated/ subdirectory:
# published image name for purposes, carino-layer-<slug> for intermediates.
layer_output_name() {
  local id="$1"
  if [[ "$id" == purpose:* ]]; then
    image_name "${id#purpose:}"
  else
    echo "carino-layer-$(layer_slug "$id")"
  fi
}

# layer_context_dir — $1 = layer id -> absolute build-context path (§9 rule:
# every layer builds with its OWN files dir as context; a generated empty stub
# stands in when the layer ships no files). The stub is created by
# emit_layer_containerfile.
layer_context_dir() {
  local id="$1"
  local files_dir
  if [[ "$id" == purpose:* ]]; then
    files_dir="${FILES_ROOT}/purposes/${id#purpose:}"
  else
    files_dir="${FILES_ROOT}/${id}"
  fi
  if [[ -d "$files_dir" ]]; then
    echo "$files_dir"
  else
    echo "${GENERATED_DIR}/$(layer_output_name "$id")/context"
  fi
}

# _kargs_slot — $1 = layer id -> §7 slot number (assigned by layer kind).
_kargs_slot() {
  case "$1" in
    base)           echo 10 ;;
    desktop-common) echo 20 ;;
    de/*)           echo 30 ;;
    purpose:*)      echo 40 ;;
    *) die "no kargs slot defined for layer kind: $1" ;;
  esac
}

# _ancestor_chain — $1 = layer id -> root-first chain ending at $1 (comment aid).
_ancestor_chain() {
  local chain="$1" cur guard=0
  load_layer_conf "$1"
  cur="$PARENT"
  while [[ -n "$cur" ]]; do
    chain="$cur $chain"
    load_layer_conf "$cur"
    cur="$PARENT"
    guard=$((guard + 1))
    (( guard <= 16 )) || die "layer chain too deep (PARENT cycle?) at '$1'"
  done
  echo "$chain"
}

# ---------------------------------------------------------------------------
# Containerfile emission
# ---------------------------------------------------------------------------

# emit_layer_containerfile — $1 = layer id (or purpose:<id>).
# Writes generated/<name>/Containerfile per §9 and guarantees a usable build
# context exists (empty stub dir when the layer has no files/ dir).
emit_layer_containerfile() {
  local id="$1"

  # ---- Resolve naming first (these helpers reload confs) -----------------
  local out_name chain ctx
  out_name="$(layer_output_name "$id")"
  chain="$(_ancestor_chain "$id")"
  ctx="$(layer_context_dir "$id")"

  # ---- Load this layer's conf and snapshot it locally --------------------
  load_layer_conf "$id"
  local description="$DESCRIPTION" parent="$PARENT" files_dir="$FILES_DIR"
  local packages="$PACKAGES" coprs="$COPRS" kargs="$KARGS" flatpaks="$FLATPAKS"
  local services_enable="$SERVICES_ENABLE" services_mask="$SERVICES_MASK"
  local post_script="$POST_SCRIPT"

  # ---- Parent image ref (root layer builds FROM the upstream base) -------
  local from_ref
  if [[ -z "$parent" ]]; then
    from_ref="$BASE_IMAGE"
  else
    from_ref="$(layer_image_ref "$parent")"
  fi

  # ---- Output locations --------------------------------------------------
  local out_dir="${GENERATED_DIR}/${out_name}"
  local cf="${out_dir}/Containerfile"
  mkdir -p "$out_dir"
  # Layers with no files dir still need a (stub) context to build from.
  if [[ ! -d "$files_dir" ]]; then
    mkdir -p "${out_dir}/context"
  fi

  local slot slug
  slot="$(_kargs_slot "$id")"
  slug="$(layer_slug "$id")"

  # ---- Write -------------------------------------------------------------
  {
    printf '# Generated by lib/generate.sh — DO NOT EDIT (regen: ./build.sh generate %s)\n' \
      "$([[ "$id" == purpose:* ]] && echo "$out_name" || echo all)"
    printf '# Layer: %s\n' "$id"
    printf '# Chain: %s\n' "$chain"
    printf '# Build: podman build -f generated/%s/Containerfile %s\n' \
      "$out_name" "${ctx#"${REPO_ROOT}"/}"
    printf '\n'
    printf 'FROM %s\n' "$from_ref"
    printf '\n'
    printf 'LABEL org.opencontainers.image.title="%s" \\\n' "$out_name"
    printf '      org.opencontainers.image.description="%s" \\\n' "$description"
    printf '      org.opencontainers.image.base.name="%s"\n' "$BASE_IMAGE" # machine-readable upstream credit: the lineage belongs in a label, not in the leading token of the image name

    # COPRs — enabled before install, left enabled (§4). fedora-bootc ships
    # dnf5 without the copr subcommand, so the plugin is installed first.
    if [[ -n "$coprs" ]]; then
      printf '\n# COPR repositories\n'
      printf "RUN dnf -y install 'dnf5-command(copr)'\n"
      local copr
      for copr in $coprs; do
        printf 'RUN dnf -y copr enable %s\n' "$copr"
      done
    fi

    # Packages
    if [[ -n "$packages" ]]; then
      printf '\n# Packages\n'
      # shellcheck disable=SC2086 — word-splitting the list is intended
      printf 'RUN dnf -y install %s && dnf clean all\n' "$(echo $packages)"
    fi

    # Files — context-relative COPY only; context IS the layer's files dir.
    if [[ -d "$files_dir" ]]; then
      printf '\n# Static files (context = %s)\n' "${files_dir#"${REPO_ROOT}"/}"
      printf 'COPY ./ /\n'
    fi

    # Services
    if [[ -n "$services_enable" ]]; then
      printf '\n# Services (enable)\n'
      # shellcheck disable=SC2086
      printf 'RUN systemctl enable %s\n' "$(echo $services_enable)"
    fi
    if [[ -n "$services_mask" ]]; then
      printf '\n# Services (mask)\n'
      # shellcheck disable=SC2086
      printf 'RUN systemctl mask %s\n' "$(echo $services_mask)"
    fi

    # Kernel args — §7 slot file /usr/lib/bootc/kargs.d/<slot>-<name>.toml
    if [[ -n "$kargs" ]]; then
      local karg toml=""
      for karg in $kargs; do
        toml+="${toml:+, }\"${karg}\""
      done
      printf '\n# Kernel arguments (slot %s)\n' "$slot"
      printf "RUN mkdir -p /usr/lib/bootc/kargs.d && \\\\\n"
      printf "    echo 'kargs = [%s]' > /usr/lib/bootc/kargs.d/%s-%s.toml\n" \
        "$toml" "$slot" "$slug"
    fi

    # Flatpaks — §8: baked as a first-boot list, never installed at build time.
    if [[ -n "$flatpaks" ]]; then
      printf '\n# Flatpak list (installed on first boot by flatpak-setup.service)\n'
      # shellcheck disable=SC2086
      printf "RUN mkdir -p /usr/share/fedora-images/flatpaks.d && \\\\\n"
      printf "    printf '%%s\\\\n' %s > /usr/share/fedora-images/flatpaks.d/%s-%s.list\n" \
        "$(echo $flatpaks)" "$slot" "$slug"
    fi

    # Post script — copied from the context, run, removed.
    if [[ -n "$post_script" ]]; then
      [[ -f "${files_dir}/${post_script}" ]] \
        || die "$id: POST_SCRIPT '$post_script' not found in ${files_dir}"
      printf '\n# Post script\n'
      printf 'COPY %s /tmp/post.sh\n' "$post_script"
      printf 'RUN chmod +x /tmp/post.sh && /tmp/post.sh && rm -f /tmp/post.sh\n'
    fi

    printf '\n# Lint the resulting bootc image\n'
    printf 'RUN bootc container lint\n'
  } > "$cf"

  info "generated ${cf#"${REPO_ROOT}"/}"
}

# ---------------------------------------------------------------------------
# Whole-image generation
# ---------------------------------------------------------------------------

# generate_image — $1 = purpose id. Emits the Containerfile of every layer in
# the purpose's chain, root-first.
generate_image() {
  local p="$1" layer
  local chain
  chain="$(layer_chain "$p")"
  info "image $(image_name "$p") — chain: $chain"
  for layer in $chain; do
    emit_layer_containerfile "$layer"
  done
}
